services:
    app:
        build:
            context: ./docker/php
        container_name: laravel-app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            PHP_IDE_CONFIG: "serverName=laravel-app"
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - mysql-data:/var/lib/mysql

    node:
        image: node:18
        container_name: laravel-node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: ["npm", "run", "dev"]
        ports:
            - "5172:5172"
        depends_on:
            - app

volumes:
    mysql-data:
